# APPLICATION
spring.application.name=smartbill-pro
server.port=9090


# DATABASE - POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/smartbill
spring.datasource.username=smartbill
spring.datasource.password=smartbill123
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

